### ISSUE TITLE
Compiles errors

### ISSUE THREAD

**Issue by dungeonsnd** [draekko/android_openssl_102d_static_libs#1]
hi, friend, 

Why android_openssl_102d_static_libs/jni/include/openssl/aes.h only contains a line?
Thank you !

$ cat jni/include/openssl/lhash.h
../../crypto/lhash/lhash.h

Many errors for that reason, e.g. :

$ $NDK/ndk-build
[armeabi] Compile thumb  : crypto <= aes_wrap.c
In file included from jni/include/openssl/err.h:127:0,
                 from jni/crypto/cryptlib.h:75,
                 from jni/crypto/aes/aes_wrap.c:55:
jni/include/openssl/lhash.h:1:1: error: expected identifier or '(' before '.' token
 ../../crypto/lhash/lhash.h
 ^

**Comment by draekko** [comment]
Not sure it compiled here before it got uploaded. It's still a work in progress, not everything is right as of last commit.

**Comment by draekko** [comment]
One thing to note I am using the latest ndk (as of today that is r10e). And the latest SDK as well.

**Comment by draekko** [comment]
Just updated for some missing files (mainly mips64 and x86_64 arch). Just tested it against tcpdump and it works fine here. Make sure to use the latest ndk and sdk.
